Create Event Handler
Shuba-Buba/Trading-propper-backtest pull request #8
Opened 2023-05-08 22:37 UTC by Shuba-Buba

2023-05-08 22:39 UTC, Shuba-Buba commented on event_handler/event_handler.go
> +	go func() {
Закрыть eventChan

2023-05-12 20:51 UTC, evlampiy-lavrentiev requested changes

2023-05-12 20:51 UTC, evlampiy-lavrentiev commented on connectors/connector.go
> +		res.socket_address = "wss://stream.binance.com:9443/ws/" + other.Symbol + "@depth@100ms"
fstream.binance.com https://binance-docs.github.io/apidocs/futures/en/#websocket-market-streams

2023-05-12 20:51 UTC, evlampiy-lavrentiev commented on connectors/connector.go
>  		if err != nil {
поч тут два раза обработка ошибки? мб я дурной и так надо, но пока не верится

2023-05-12 20:51 UTC, evlampiy-lavrentiev commented on contracts/contracts.go
> +	MarketName  string `json:"stock_market_name"` // не придумал ничего умнее
всё-таки если говорить про биржи то лучше подойдёт Exchange а не Market

2023-05-12 20:58 UTC, Shuba-Buba commented on connectors/connector.go
> +		res.socket_address = "wss://stream.binance.com:9443/ws/" + other.Symbol + "@depth@100ms"
Исправит сам Амир Камалов)

2023-05-12 21:03 UTC, merged

2023-05-13 08:30 UTC, evlampiy-lavrentiev commented on postman/postman.go
>  	cur_free_port := 0
cur_free_port --> free_port_index ? cur_free_port это не порт а отступ, название переменной дезинформирует о том что в ней содержится